source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'InkExampleiOS', :exclusive => true do
  pod 'InkKit', :path => '../'
end

target 'InkExampleOSX', :exclusive => true do
  pod 'InkKit', :path => '../'
end

