source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'InkExampleiOS' do
  platform :ios, '8.0'
    
  pod 'InkKit', :path => '../'
end

target 'InkExampleOSX' do
  platform :osx, '10.10'
  
  pod 'InkKit', :path => '../'
end
